apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: airflow
  name: airflow-dags-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  volumeName: airflow-dags-pv
  accessModes:
  - ReadWriteMany