---
airflowVersion: 2.2.3
executor: KubernetesExecutor
webserver:
  defaultUser:
    enabled: True

data:
  metadataConnection:
    db: postgres
    host: OverrideDuringDeployment
    pass: OverrideDuringDeployment
    port: 5432
    protocol: postgresql+psycopg2
    user: OverrideDuringDeployment
    sslmode: prefer

postgresql:
  enabled: False

scheduler:
  safeToEvict: True

workers:
  safeToEvict: False

flower:
  enabled: False

redis:
  enabled: False

---